Completed Two Column Layout Exercise
maryalenn/m1-0122-code-solutions pull request #19
Opened 2022-02-10 03:32 UTC by maryalenn

![css-two-column-layout](https://user-images.githubusercontent.com/97073517/153332083-2e415426-f9f8-4ba0-87af-4d8fdb3200b8.png)

2022-02-10 18:45 UTC, BrettAlbright requested changes
Looks great! A few updates are requested

2022-02-10 18:45 UTC, BrettAlbright commented on css-two-column-layout/styles.css
> +  width:80%;
I would recommend a fixed width for the container, and percentages for the columns and rows.

2022-02-10 18:45 UTC, BrettAlbright commented on css-two-column-layout/styles.css
> +.col {
always make sure you explicitly set your column widths. While flex box will automatically generate a size for child elements so they fit evenly in their parent, that cannot be relied upon for stable website layouts

2022-02-10 18:45 UTC, BrettAlbright commented on css-two-column-layout/index.html
> +      <div class="col">
There should be a `row` class which contains the `column` classes, make sure to reference the `layout classes` exercise.

2022-02-11 02:22 UTC, maryalenn commented
Thanks Brett - revisions made
![image](https://user-images.githubusercontent.com/97073517/153528322-ad778440-8608-42e3-9aa1-40cf20f14c1d.png)

2022-02-11 02:35 UTC, Zhiwutian approved these changes
👍🏼

2022-02-11 02:36 UTC, merged